### ISSUE TITLE
Wrap / unwrap ETH & GNT

### ISSUE THREAD

**Issue by deepinit-arek** [OasisDEX/oasis-react#85]
- [x]  Implement **OasisWrapUnwrapBalances** component ( #98  ). 
- [ ]  Implement **wrapUnwrap** reducer actions. ( #101 ).
- [x]  Implement **OasisWrapUnwrapHistory** component ( #97 ).
- [x]  Implement **wrapUnwrapHistory** reducer actions (  #100 ).  
- [ ]  Implement **OasisWrapUnwrapWrap** component ( #98  ).   
- [ ]  Implement **OasisWrapUnwrapUnwrap** component ( #95  ).
